apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hello-world-1cqe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hello-world-1cqe
    app.kubernetes.io/part-of: test-app-lwdl
  name: devfile-sample-hello-world-1cqe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: devfile-sample-hello-world-1cqe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: devfile-sample-hello-world-1cqe
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-vdot-tenant/test-app-lwdl/devfile-sample-hello-world-1cqe@sha256:66411b57a18fddf8057658189d43a0323b0664e6afcd5d75990715ee066828da
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
